
ALTER TABLE receivables
ADD COLUMN tds_applicable BOOLEAN NOT NULL DEFAULT FALSE,
ADD COLUMN tds_rate DECIMAL(5,2) NULL,
ADD COLUMN tds_amount DECIMAL(15,2) NOT NULL DEFAULT 0.00,
ADD COLUMN tds_description VARCHAR(255) NULL;